### ISSUE TITLE
Add table net_certificate_logs

### ISSUE THREAD

**Issue by aidansteele** [turbot/steampipe-plugin-net#10]
# General background / value proposition

[Certificate transparency logs](https://certificate.transparency.dev/) provide a publicly-accessible record of almost all SSL certificates issued on the Internet. It could be helpful to be able to query these tables from Steampipe to e.g. validate that no certificates have been issued for my domains that weren't in AWS ACM for one of my accounts.

# Implementation questions

The question becomes: which data source should this query? A popular one is https://crt.sh. In fact, they even provide a publicly available Postgres instance (!!) for querying CT logs. You can get a sample of the SQL at this URL: https://crt.sh/?q=%25.steampipe.io&showSQL=y.

That page uses this SQL query:

```sql
WITH ci AS (
    SELECT min(sub.CERTIFICATE_ID) ID,
           min(sub.ISSUER_CA_ID) ISSUER_CA_ID,
           array_agg(DISTINCT sub.NAME_VALUE) NAME_VALUES,
           x509_commonName(sub.CERTIFICATE) COMMON_NAME,
           x509_notBefore(sub.CERTIFICATE) NOT_BEFORE,
           x509_notAfter(sub.CERTIFICATE) NOT_AFTER,
           encode(x509_serialNumber(sub.CERTIFICATE), 'hex') SERIAL_NUMBER
        FROM (SELECT *
                  FROM certificate_and_identities cai
                  WHERE plainto_tsquery('certwatch', 'steampipe.io') @@ identities(cai.CERTIFICATE)
                      AND cai.NAME_VALUE ILIKE ('%' || 'steampipe.io' || '%')
                  LIMIT 10000
             ) sub
        GROUP BY sub.CERTIFICATE
)
SELECT ci.ISSUER_CA_ID,
        ca.NAME ISSUER_NAME,
        ci.COMMON_NAME,
        array_to_string(ci.NAME_VALUES, chr(10)) NAME_VALUE,
        ci.ID ID,
        le.ENTRY_TIMESTAMP,
        ci.NOT_BEFORE,
        ci.NOT_AFTER,
        ci.SERIAL_NUMBER
    FROM ci
            LEFT JOIN LATERAL (
                SELECT min(ctle.ENTRY_TIMESTAMP) ENTRY_TIMESTAMP
                    FROM ct_log_entry ctle
                    WHERE ctle.CERTIFICATE_ID = ci.ID
            ) le ON TRUE,
         ca
    WHERE ci.ISSUER_CA_ID = ca.ID
    ORDER BY le.ENTRY_TIMESTAMP DESC NULLS LAST;
```

That yields (at the time of writing) these results: 
<img width="2047" alt="screenshot of psql" src="https://user-images.githubusercontent.com/369053/127589661-f4a86f20-8e14-4c4e-b26e-c52b6fecfb51.png">

That presents us with a few questions:

* Would you just use the Postgres->Postgres `postgres_fdw` with host `crt.sh`, user `guest` and DB `certwatch`?
* Or should Steampipe attempt to simplify the (quite complex!) query above with some kind of view?
* Maybe it's not worth using the `postgres_fdw` because it doesn't work with Steampipe's architecture, e.g. caching (I say this from a point of ignorance, I haven't looked into how that works)

Either way, I feel this could be useful. Thoughts?

**Comment by e-gineer** [comment]
@aidansteele Great idea for a table!

I researched this idea a while back actually ... will share some of my (incomplete) work below.

Here are a list of possible sources for certificate transparency I found:
- https://github.com/knqyf263/crtsh for https://crt.sh/
- https://transparencyreport.google.com/https/certificates
- https://developers.facebook.com/docs/certificate-transparency-api/
- https://sslmate.com/certspotter/api/
- https://certificate.transparency.dev/monitors/
- https://github.com/google/certificate-transparency-go

While I loved the idea of a certificate transparency table, none of these options jumped out at me as being great.

It's fascinating that crt.sh works as a public postgres database, but I have seen variable performance when connecting to it during testing. In the end it seemed best to just go with the simplest steampipe wrapper FDW. (I agree that using other FDW's in steampipe could be awesome - e.g. postgres_fdw, sqlite_fdw).

**Comment by aidansteele** [comment]
That's a great point regarding reliability and performance. You wouldn't want your rules to start failing because of third-party dependencies. Tricky 🤔
